#
# NOTE: this runs the omnibus cookbook, but does not actually run Omnibus. Use
# 'kichen converge' to setup the virtual machine and then `kitchen login` to
# SSH into the machine and run Omnibus.
#

driver:
  name: vagrant
  forward_agent: yes
  customize:
    cpus: 4
    memory: 4096
  synced_folders:
    - ['.', '/home/vagrant/omnibus-chef']
    - ['../omnibus', '/home/vagrant/omnibus']
    - ['../omnibus-software', '/home/vagrant/omnibus-software']

provisioner:
  name: chef_zero
  require_chef_omnibus: 11.14.6

platforms:
  - name: centos-5.10
    run_list: yum-epel::default
  - name: centos-6.5
    run_list: yum-epel::default
  - name: debian-7.2.0
    run_list: apt::default
  - name: debian-7.4
    run_list: apt::default
  - name: debian-6.0.8
    run_list: apt::default
  - name: freebsd-9.2
    run_list: freebsd::portsnap
  - name: ubuntu-10.04
    run_list: apt::default
  - name: ubuntu-12.04
    run_list: apt::default
  - name: ubuntu-12.10
    run_list: apt::default
  - name: ubuntu-13.04
    run_list: apt::default
  - name: ubuntu-13.10
    run_list: apt::default
  - name: ubuntu-14.04
    run_list: apt::default
  - name: windows-7-professional
    provisioner:
      name: windows_chef_zero
  - name: windows-8.1-professional
    provisioner:
      name: windows_chef_zero

suites:
  - name: chef
    run_list: omnibus::default
    attributes:
      omnibus:
        build_user:  vagrant
        build_dir:   /home/vagrant/chef
        install_dir: /opt/chef
  - name: chefdk
    run_list: omnibus::default
    attributes:
      omnibus:
        build_user:  vagrant
        build_dir:   /home/vagrant/chefdk
        install_dir: /opt/chefdk
  - name: chef-container
    run_list:
      - omnibus::default
      - docker::default
    attributes:
      omnibus:
        build_user:  vagrant
        build_dir:   /home/vagrant/chef-container
        install_dir: /opt/chef-container
