# NOTE: this runs the omnibus cookbook, but doens't mount filesystems or
# run omnibus yet.  Use 'kichen converge' to setup the virt and install
# omnibus cookbooks and then be able to login to it

driver:
  name: vagrant
  customize:
    memory: 2048
    cpus: 4
  synced_folders:
    - ['.', '/home/vagrant/omnibus-chef', type: 'rsync']

provisioner:
  name: chef_zero
  require_chef_omnibus: true

platforms:
  - name: centos-5.10
    run_list: yum-epel::default
  - name: centos-6.5
    run_list: yum-epel::default
  - name: debian-7.2.0
    run_list: apt::default
  - name: debian-6.0.8
    run_list: apt::default
  - name: freebsd-9.2
    run_list: freebsd::portsnap
  - name: ubuntu-10.04
    run_list: apt::default
  - name: ubuntu-12.04
    run_list: apt::default
  - name: ubuntu-12.10
    run_list: apt::default
  - name: ubuntu-13.04
    run_list: apt::default
  - name: ubuntu-13.10
    run_list: apt::default
  - name: ubuntu-14.04
    run_list: apt::default

suites:
  - name: chef
    attributes:
      omnibus:
        build_user: vagrant
        install_dir: /opt/chef
    run_list: omnibus::default
  - name: chefdk
    attributes:
      omnibus:
        build_user: vagrant
        install_dir: /opt/chefdk
    run_list: omnibus::default
  - name: chef-container
    attributes:
      omnibus:
        build_user: vagrant
        install_dir: /opt/chef
    run_list: 
      - omnibus::default
      - docker::default
