#
# NOTE: this runs the omnibus cookbook, but does not actually run Omnibus. Use
# 'kichen converge' to setup the virtual machine and then `kitchen login` to
# SSH into the machine and run Omnibus.
#

driver:
  name: vagrant
  forward_agent: yes
  customize:
    cpus: 4
    memory: 4096
  synced_folders:
    - ['.', '/home/vagrant/omnibus-chef']
    - ['../omnibus', '/home/vagrant/omnibus']
    - ['../omnibus-software', '/home/vagrant/omnibus-software']

provisioner:
  name: chef_zero
  require_chef_omnibus: 11.16.4

platforms:
  - name: centos-5.10
    run_list: yum-epel::default
  - name: centos-6.5
    run_list: yum-epel::default
  - name: debian-7.2.0
    run_list: apt::default
  - name: debian-7.4
    run_list: apt::default
  - name: debian-6.0.8
    run_list: apt::default
  - name: freebsd-9.2
    run_list:
      - freebsd::portsnap
      - freebsd::pkgng
  - name: freebsd-10.0
    run_list: freebsd::portsnap
  - name: ubuntu-10.04
    run_list: apt::default
  - name: ubuntu-12.04
    run_list: apt::default
  - name: ubuntu-12.10
    run_list: apt::default
  - name: ubuntu-13.04
    run_list: apt::default
  - name: ubuntu-13.10
    run_list: apt::default
  - name: ubuntu-14.04
    run_list: apt::default
  # The following boxes are shared via VagrantCloud. Until kitchen-vagrant
  # is updated you'll need to add the box manually:
  #
  #   vagrant box add chef/windows-8.1-professional
  #
  # Please note this may require a `vagrant login` if the box is private.
  #
  # The following boxes are VMware only also. You can enable VMware Fusion
  # as the default provider by copying `.kitchen.local.yml.vmware.example`
  # over to `.kitchen.local.yml`.
  #
  - name: macosx-10.8
    driver:
      box: chef/macosx-10.8 # private
  - name: macosx-10.9
    driver:
      box: chef/macosx-10.9 # private
  - name: macosx-10.10
    driver:
      box: chef/macosx-10.10 # private
  - name: windows-7-professional
    provisioner:
      name: windows_chef_zero
      require_chef_omnibus: 11.12.4
    driver:
      box: chef/windows-7-professional # private
  - name: windows-8.1-professional
    provisioner:
      name: windows_chef_zero
      require_chef_omnibus: 11.12.4
    driver:
      box: chef/windows-8.1-professional # private
  - name: windows-2008r2-standard
    provisioner:
      name: windows_chef_zero
      require_chef_omnibus: 11.12.4
    driver:
      box: chef/windows-server-2008r2-standard # private

attribute_defaults: &attribute_defaults
  build_user:          vagrant
  build_user_group:    vagrant
  build_user_password: vagrant

suites:
  - name: angrychef
    attributes:
      omnibus:
        <<: *attribute_defaults
        install_dir: /opt/angrychef
    run_list:
      - omnibus::default
  - name: chef
    attributes:
      omnibus:
        <<: *attribute_defaults
        install_dir: /opt/chef
    run_list:
      - omnibus::default
  - name: chefdk
    attributes:
      omnibus:
        <<: *attribute_defaults
        install_dir: /opt/chefdk
    run_list:
      - omnibus::default
  - name: chef-container
    attributes:
      omnibus:
        <<: *attribute_defaults
        install_dir: /opt/chef-container
    run_list:
      - omnibus::default
      - docker::default
  - name: push-jobs-client
    attributes:
      omnibus:
        <<: *attribute_defaults
        install_dir: /opt/push-jobs-client
    run_list:
      - omnibus::default
