#!/bin/bash
#
# Build you some jenkins
#

set -e
set -x

# Check whether a command exists - returns 0 if it does, 1 if it does not
exists()
{
  if command -v $1 &>/dev/null
  then
    return 0
  else
    return 1
  fi
}

usage()
{
  echo >&2 \
  "usage: $0 [-p project_name]"
}

# Get command line arguments
while getopts :p: opt
do
  echo $opt
  case "$opt" in
    p)  project_name="$OPTARG";;
    [\?]|[\:]) usage; exit 1;;
  esac
done

if [ -z $project_name ]
then
  usage
  exit 1
fi

# create the build timestamp file for fingerprinting if it doesn't exist (manual build execution)
if [ ! -f build_timestamp ]
then
  date > build_timestamp
  echo "$BUILD_TAG / $BUILD_ID" > build_timestamp
fi

if [ "$CLEAN" = "true" ]; then
  sudo rm -rf /opt/$project_name || true
  sudo rm -rf /var/cache/omnibus || true
  sudo rm -f pkg/* || true
fi

# create required build dirs and set ownership
for BUILD_DIR in /opt/$project_name /var/cache/omnibus
do
  sudo mkdir -p $BUILD_DIR
  sudo chown $(whoami) $BUILD_DIR
done

# copy config into place
cp omnibus.rb.example omnibus.rb

# execute build via omnibus rake task
bundle install --deployment
bundle exec rake "projects:${project_name}"

# Sign the package on some platforms:
if exists rpm;
then
  sudo -i $(pwd)/jenkins/sign-rpm "foo" $(pwd)/pkg/*rpm
fi

# Dump the build-generated version so the Omnitruck release script uses the
# correct version string format.
echo "`awk -v p=$project_name '$1 == p {print $2}' /opt/${project_name}/version-manifest.txt`" > pkg/BUILD_VERSION
