#!/bin/bash

INSTALLER_DIR=/opt/chef

# Clean up binary symlinks if they exist
# see: http://tickets.opscode.com/browse/CHEF-3022
if [ ! -e /etc/redhat-release -o "x$1" == "x0" ]; then
  for i in chef-client chef-solo chef-apply chef-shell knife shef ohai ; do
    if [ "x${INSTALLER_DIR}/bin/${i}" == x`readlink /usr/bin/${i}` ]; then
      rm -f /usr/bin/${i}
    fi
  done
fi
